[/Script/Puerts.PuertsSetting]
; Core UE modules
+ModuleWhiteListOnDTS=CoreUObject
+ModuleWhiteListOnDTS=Engine
+ModuleWhiteListOnDTS=InputCore
+ModuleWhiteListOnDTS=UMG
+ModuleWhiteListOnDTS=SlateCore
+ModuleWhiteListOnDTS=Slate
; Editor modules
+ModuleWhiteListOnDTS=UnrealEd
+ModuleWhiteListOnDTS=Blutility
; PuerTS modules
+ModuleWhiteListOnDTS=JsEnv
+ModuleWhiteListOnDTS=Puerts
; Project modules
+ModuleWhiteListOnDTS=TestPuerTS
+ModuleWhiteListOnDTS=TestPuerTSEditor
+ModuleWhiteListOnDTS=TsEditor
+ModuleWhiteListOnDTS=EditorCommon
