[/Script/Puerts.PuertsSetting]
; Core UE modules
+ModuleWhiteListOnDTS=CoreUObject
+ModuleWhiteListOnDTS=Engine
+ModuleWhiteListOnDTS=InputCore
+ModuleWhiteListOnDTS=EnhancedInput
+ModuleWhiteListOnDTS=AnimGraphRuntime
+ModuleWhiteListOnDTS=UMG
+ModuleWhiteListOnDTS=SlateCore
+ModuleWhiteListOnDTS=Slate
; Editor modules
+ModuleWhiteListOnDTS=UnrealEd
+ModuleWhiteListOnDTS=UMGEditor
+ModuleWhiteListOnDTS=AnimGraph
+ModuleWhiteListOnDTS=Blutility
+ModuleWhiteListOnDTS=VREditor
+ModuleWhiteListOnDTS=LevelSequence
+ModuleWhiteListOnDTS=PropertyEditor
+ModuleWhiteListOnDTS=ScriptableEditorWidgets
+ModuleWhiteListOnDTS=TakeRecorder
+ModuleWhiteListOnDTS=AdvancedWidgets
+ModuleWhiteListOnDTS=AudioWidgets
+ModuleWhiteListOnDTS=Synthesis
+ModuleWhiteListOnDTS=ObjectMixerEditor
; PuerTS modules
+ModuleWhiteListOnDTS=JsEnv
+ModuleWhiteListOnDTS=Puerts
; Project modules
+ModuleWhiteListOnDTS=TestPuerTS
+ModuleWhiteListOnDTS=TestPuerTSEditor
+ModuleWhiteListOnDTS=TsEditor
+ModuleWhiteListOnDTS=EditorCommon
+ModuleWhiteListOnDTS=ReactUMG
